"""Tests for PHP language support."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from diffguard.ast import (
    Language,
    detect_language,
    extract_imports,
    find_used_symbols,
    is_first_party,
    parse_file,
    resolve_symbol_definition,
)
from diffguard.ast.php import _extract_namespace, clear_composer_cache
from diffguard.ast.python import Import
from diffguard.ast.scope import find_enclosing_scope
from diffguard.config import DiffguardConfig
from diffguard.exclusions import is_generated_file
from diffguard.git import DiffFile, DiffHunk
from diffguard.pipeline import _filter_analyzable_files

if TYPE_CHECKING:
    from tree_sitter import Tree


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_php(source: str) -> Tree:
    """Parse PHP source and return a tree-sitter Tree."""
    tree = parse_file(source, Language.PHP)
    assert tree is not None
    return tree


def _make_diff_file(path: str) -> DiffFile:
    return DiffFile(
        old_path=path,
        new_path=path,
        hunks=[DiffHunk(old_start=1, old_count=1, new_start=1, new_count=1, lines=[("+", "x")])],
        is_new_file=False,
        is_deleted=False,
        is_binary=False,
    )


# ---------------------------------------------------------------------------
# Test fixtures
# ---------------------------------------------------------------------------

PHP_CONTROLLER = """\
<?php
namespace App\\Controllers;

use App\\Services\\Helper;
use App\\Models\\User;
use App\\Models\\{Post, Comment};
use Symfony\\Component\\HttpFoundation\\Request;

require_once __DIR__ . '/../bootstrap.php';

class UserController
{
    private UserService $userService;

    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    public function create(Request $request): User
    {
        $data = $request->toArray();
        Helper::validate($data);
        return new User($data);
    }

    public static function routes(): array
    {
        return ['/users', '/users/{id}'];
    }
}
"""

PHP_TRAIT = """\
<?php
namespace App\\Traits;

trait Timestampable
{
    private ?\\DateTimeInterface $createdAt = null;
    private ?\\DateTimeInterface $updatedAt = null;

    public function setCreatedAt(\\DateTimeInterface $date): void
    {
        $this->createdAt = $date;
    }

    public function getCreatedAt(): ?\\DateTimeInterface
    {
        return $this->createdAt;
    }
}
"""

PHP_INTERFACE = """\
<?php
namespace App\\Contracts;

interface RepositoryInterface
{
    public function find(int $id): ?object;
    public function findAll(): array;
    public function save(object $entity): void;
    public function delete(int $id): void;
}
"""

PHP_CLOSURES = """\
<?php
namespace App\\Services;

class Calculator
{
    public function process(array $items): array
    {
        $multiplier = 2;

        $doubled = array_map(function($x) use ($multiplier) {
            return $x * $multiplier;
        }, $items);

        $tripled = array_map(fn($x) => $x * 3, $items);

        return $doubled;
    }
}
"""

PHP_ATTRIBUTES = """\
<?php
namespace App\\Controllers;

use App\\Attributes\\Route;
use App\\Attributes\\Middleware;

#[Route('/api/v1')]
#[Middleware('auth')]
class ApiController
{
    #[Route('/users', methods: ['GET'])]
    public function index(): array
    {
        return [];
    }
}
"""

PHP_STANDALONE_FUNCTION = """\
<?php
function standalone_helper($input) {
    return strtolower($input);
}

function process(string $input): array {
    return explode(',', $input);
}
"""

PHP_GENERATED = """\
<?php // auto-generated by some tool
namespace App\\Generated;

class GeneratedDto {
    private string $field;
}
"""


# ---------------------------------------------------------------------------
# Language Detection
# ---------------------------------------------------------------------------


class TestPhpLanguageDetection:
    def test_detect_php_extension(self) -> None:
        assert detect_language("app/Controllers/UserController.php") == Language.PHP

    def test_detect_php_simple(self) -> None:
        assert detect_language("index.php") == Language.PHP

    def test_detect_non_php(self) -> None:
        assert detect_language("main.py") != Language.PHP

    def test_parse_valid_php(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        assert tree is not None
        assert tree.root_node.type == "program"


# ---------------------------------------------------------------------------
# Scope Detection
# ---------------------------------------------------------------------------


class TestPhpScopeDetection:
    def test_function_scope(self) -> None:
        tree = _parse_php(PHP_STANDALONE_FUNCTION)
        # Line inside standalone_helper function body (line 3: `return strtolower($input);`)
        scope = find_enclosing_scope(tree, 3, Language.PHP)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "standalone_helper"

    def test_function_with_type_hints(self) -> None:
        tree = _parse_php(PHP_STANDALONE_FUNCTION)
        # Line inside process function (line 7: `return explode(',', $input);`)
        scope = find_enclosing_scope(tree, 7, Language.PHP)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "process"

    def test_class_scope(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # Line inside class body but not in a method (line 13: `private UserService $userService;`)
        scope = find_enclosing_scope(tree, 13, Language.PHP)
        assert scope is not None
        assert scope.type == "class"
        assert scope.name == "UserController"

    def test_method_scope(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # Line inside `create` method body (line 23: `$data = $request->toArray();`)
        scope = find_enclosing_scope(tree, 23, Language.PHP)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "create"

    def test_static_method_scope(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # Line inside `routes` static method (line 30: `return ['/users', '/users/{id}'];`)
        scope = find_enclosing_scope(tree, 30, Language.PHP)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "routes"

    def test_private_method_scope(self) -> None:
        source = """\
<?php
class Validator {
    private function validate($data) {
        return true;
    }
}
"""
        tree = _parse_php(source)
        scope = find_enclosing_scope(tree, 4, Language.PHP)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "validate"

    def test_constructor_scope(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # Line inside __construct (line 17: `$this->userService = $userService;`)
        scope = find_enclosing_scope(tree, 17, Language.PHP)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "__construct"

    def test_trait_scope(self) -> None:
        tree = _parse_php(PHP_TRAIT)
        # Line inside trait body but not in a method (line 6: `private ?\\DateTimeInterface $createdAt = null;`)
        scope = find_enclosing_scope(tree, 6, Language.PHP)
        assert scope is not None
        assert scope.type == "trait"
        assert scope.name == "Timestampable"

    def test_interface_scope(self) -> None:
        tree = _parse_php(PHP_INTERFACE)
        # Line inside interface body (line 4: `interface RepositoryInterface`)
        scope = find_enclosing_scope(tree, 4, Language.PHP)
        assert scope is not None
        assert scope.type == "interface"
        assert scope.name == "RepositoryInterface"

    def test_anonymous_function_scope(self) -> None:
        tree = _parse_php(PHP_CLOSURES)
        # Line inside the anonymous function (line 11: `return $x * $multiplier;`)
        scope = find_enclosing_scope(tree, 11, Language.PHP)
        assert scope is not None
        assert scope.type == "closure"
        assert scope.name == "<anonymous>"

    def test_arrow_function_scope(self) -> None:
        tree = _parse_php(PHP_CLOSURES)
        # Line 14 has the arrow function: `$tripled = array_map(fn($x) => $x * 3, $items);`
        scope = find_enclosing_scope(tree, 14, Language.PHP)
        assert scope is not None
        # Arrow function is contained in the method
        assert scope.type in ("arrow_function", "method")

    def test_no_scope_at_php_tag(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # Line 1: `<?php`
        scope = find_enclosing_scope(tree, 1, Language.PHP)
        assert scope is None


# ---------------------------------------------------------------------------
# Import Extraction
# ---------------------------------------------------------------------------


class TestPhpImportExtraction:
    def test_use_single_class(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        imports = extract_imports(tree, Language.PHP)
        modules = [imp.module for imp in imports]
        assert any("Helper" in m for m in modules)

    def test_use_with_alias(self) -> None:
        source = """\
<?php
use App\\Services\\Helper as H;
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert imports[0].alias == "H"

    def test_grouped_use(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        imports = extract_imports(tree, Language.PHP)
        # Should find Post and Comment from grouped use
        all_names = []
        for imp in imports:
            if imp.names:
                all_names.extend(imp.names)
        assert "Post" in all_names
        assert "Comment" in all_names

    def test_use_function(self) -> None:
        source = """\
<?php
use function App\\Helpers\\format_date;
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert "format_date" in (imports[0].names or [])

    def test_use_const(self) -> None:
        source = """\
<?php
use const App\\Config\\DEBUG;
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert "DEBUG" in (imports[0].names or [])

    def test_require_statement(self) -> None:
        source = """\
<?php
require 'helper.php';
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert imports[0].module == "helper.php"

    def test_require_once_statement(self) -> None:
        source = """\
<?php
require_once 'bootstrap.php';
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert imports[0].module == "bootstrap.php"

    def test_include_statement(self) -> None:
        source = """\
<?php
include 'template.php';
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert imports[0].module == "template.php"

    def test_include_once_statement(self) -> None:
        source = """\
<?php
include_once 'config.php';
"""
        tree = _parse_php(source)
        imports = extract_imports(tree, Language.PHP)
        assert len(imports) == 1
        assert imports[0].module == "config.php"

    def test_multiple_imports(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        imports = extract_imports(tree, Language.PHP)
        # Helper, User, {Post, Comment}, Request, require_once = at least 6
        assert len(imports) >= 6


# ---------------------------------------------------------------------------
# Symbol Usage Detection
# ---------------------------------------------------------------------------


class TestPhpSymbolUsage:
    def test_used_symbols_in_method(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # `create` method lines 21-26: references Helper, User
        symbols = find_used_symbols(tree, 21, 26, Language.PHP)
        assert "Helper" in symbols

    def test_excludes_builtins(self) -> None:
        tree = _parse_php(PHP_STANDALONE_FUNCTION)
        # Line 3: `return strtolower($input);` — strtolower is builtin
        symbols = find_used_symbols(tree, 2, 4, Language.PHP, exclude_builtins=True)
        assert "strtolower" not in symbols

    def test_method_name_excluded(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        # Method definition names should not be in used symbols
        symbols = find_used_symbols(tree, 15, 18, Language.PHP)
        assert "__construct" not in symbols


# ---------------------------------------------------------------------------
# First-Party Detection
# ---------------------------------------------------------------------------


class TestPhpFirstPartyDetection:
    def test_first_party_with_composer_psr4(self, tmp_path: Path) -> None:
        clear_composer_cache()
        composer = {
            "autoload": {"psr-4": {"App\\": "src/"}},
        }
        (tmp_path / "composer.json").write_text(json.dumps(composer))
        assert is_first_party("App\\Services\\Helper", tmp_path, [], Language.PHP) is True

    def test_third_party_namespace(self, tmp_path: Path) -> None:
        clear_composer_cache()
        composer = {
            "autoload": {"psr-4": {"App\\": "src/"}},
        }
        (tmp_path / "composer.json").write_text(json.dumps(composer))
        assert is_first_party("Symfony\\Component\\HttpFoundation\\Request", tmp_path, [], Language.PHP) is False

    def test_first_party_with_relative_path(self) -> None:
        root = Path("/project")
        assert is_first_party("./helper.php", root, [], Language.PHP, is_relative=True) is True

    def test_first_party_with_multiple_psr4(self, tmp_path: Path) -> None:
        clear_composer_cache()
        composer = {
            "autoload": {"psr-4": {"App\\": "src/", "Tests\\": "tests/"}},
        }
        (tmp_path / "composer.json").write_text(json.dumps(composer))
        assert is_first_party("App\\Models\\User", tmp_path, [], Language.PHP) is True
        assert is_first_party("Tests\\Unit\\UserTest", tmp_path, [], Language.PHP) is True

    def test_no_composer_json(self, tmp_path: Path) -> None:
        clear_composer_cache()
        assert is_first_party("App\\Services\\Helper", tmp_path, [], Language.PHP) is False


# ---------------------------------------------------------------------------
# Symbol Resolution
# ---------------------------------------------------------------------------


class TestPhpSymbolResolution:
    def test_resolve_use_to_file(self, tmp_path: Path) -> None:
        clear_composer_cache()
        composer = {"autoload": {"psr-4": {"App\\": "src/"}}}
        (tmp_path / "composer.json").write_text(json.dumps(composer))
        src_dir = tmp_path / "src" / "Services"
        src_dir.mkdir(parents=True)
        helper_file = src_dir / "UserService.php"
        helper_file.write_text("<?php\nnamespace App\\Services;\n")

        imports = [Import(module="App\\Services\\UserService", names=["UserService"])]
        result = resolve_symbol_definition("UserService", imports, tmp_path, None, Language.PHP)
        assert result is not None
        assert result == helper_file

    def test_resolve_unresolvable_returns_none(self, tmp_path: Path) -> None:
        clear_composer_cache()
        imports = [Import(module="App\\Unknown\\Thing", names=["Thing"])]
        result = resolve_symbol_definition("Thing", imports, tmp_path, None, Language.PHP)
        assert result is None

    def test_resolve_no_matching_import(self, tmp_path: Path) -> None:
        imports = [Import(module="App\\Other\\Class", names=["Class"])]
        result = resolve_symbol_definition("Helper", imports, tmp_path, None, Language.PHP)
        assert result is None


# ---------------------------------------------------------------------------
# Vendor Path Filtering
# ---------------------------------------------------------------------------


class TestPhpVendorPathFiltering:
    def test_skip_composer_vendor(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("vendor/symfony/http-foundation/Request.php")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 0

    def test_skip_vendor_autoload(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("vendor/autoload.php")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 0

    def test_normal_php_file_kept(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("app/Controllers/UserController.php")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 1


# ---------------------------------------------------------------------------
# Generated/Cache File Detection
# ---------------------------------------------------------------------------


class TestPhpGeneratedFileDetection:
    def test_skip_symfony_cache(self) -> None:
        assert is_generated_file("var/cache/prod/ContainerAbcdef.php", [], Language.PHP) is True

    def test_skip_laravel_bootstrap_cache(self) -> None:
        assert is_generated_file("bootstrap/cache/packages.php", [], Language.PHP) is True

    def test_skip_laravel_storage_cache(self) -> None:
        assert is_generated_file("storage/framework/cache/data/abc.php", [], Language.PHP) is True

    def test_skip_auto_generated_header(self) -> None:
        lines = PHP_GENERATED.splitlines()
        assert is_generated_file("src/Generated/GeneratedDto.php", lines, Language.PHP) is True

    def test_skip_generated_annotation(self) -> None:
        lines = ["<?php", "// @generated by some tool", "class Foo {}"]
        assert is_generated_file("src/Foo.php", lines, Language.PHP) is True

    def test_normal_php_not_generated(self) -> None:
        lines = PHP_CONTROLLER.splitlines()
        assert is_generated_file("app/Controllers/UserController.php", lines, Language.PHP) is False

    def test_filter_analyzable_skips_cache_file(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("var/cache/prod/Container.php")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 0


# ---------------------------------------------------------------------------
# Parsing Features
# ---------------------------------------------------------------------------


class TestPhpParsingFeatures:
    def test_parse_namespace(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        ns = _extract_namespace(tree)
        assert ns is not None
        assert "Controllers" in ns

    def test_parse_attributes(self) -> None:
        tree = _parse_php(PHP_ATTRIBUTES)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_typed_properties(self) -> None:
        tree = _parse_php(PHP_CONTROLLER)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_constructor_promotion(self) -> None:
        source = """\
<?php
class Service {
    public function __construct(
        private string $name,
        protected int $count = 0,
    ) {}
}
"""
        tree = _parse_php(source)
        assert tree is not None

    def test_parse_trait(self) -> None:
        tree = _parse_php(PHP_TRAIT)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_interface(self) -> None:
        tree = _parse_php(PHP_INTERFACE)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_closures(self) -> None:
        tree = _parse_php(PHP_CLOSURES)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_arrow_function(self) -> None:
        source = """\
<?php
$fn = fn($x) => $x * 2;
"""
        tree = _parse_php(source)
        assert tree is not None
