"""Tests for Go language support and Makefile detection."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from diffguard.ast import extract_imports, find_enclosing_scope, find_used_symbols, parse_file
from diffguard.ast.go import (
    clear_go_mod_cache,
    extract_go_imports,
    find_go_scope,
    find_go_used_symbols,
    is_first_party_go,
    resolve_go_symbol,
)
from diffguard.ast.languages import Language, detect_language
from diffguard.ast.python import Import
from diffguard.config import DiffguardConfig
from diffguard.exclusions import is_generated_file

if TYPE_CHECKING:
    from tree_sitter import Tree

# ---------------------------------------------------------------------------
# Test fixtures
# ---------------------------------------------------------------------------

GO_PACKAGE = """\
package main

import (
    "fmt"
    "strings"
    "net/http"

    "github.com/myorg/myapp/internal/helper"
    _ "github.com/lib/pq"
)

type Service struct {
    config Config
}

func NewService(config Config) *Service {
    return &Service{config: config}
}

func (s *Service) Process(input string) string {
    return helper.Sanitize(strings.TrimSpace(input))
}

func (s Service) GetConfig() Config {
    return s.config
}

func main() {
    fmt.Println("Hello")
}
"""

GO_INTERFACE = """\
package storage

type Repository interface {
    FindByID(id string) (*Entity, error)
    FindAll() ([]*Entity, error)
    Save(entity *Entity) error
    Delete(id string) error
}
"""

GO_GOROUTINE = """\
package worker

func ProcessAsync(items []Item) {
    for _, item := range items {
        go func(i Item) {
            process(i)
        }(item)
    }
}
"""

GO_ERROR_HANDLING = """\
package service

func LoadConfig(path string) (*Config, error) {
    file, err := os.Open(path)
    if err != nil {
        return nil, fmt.Errorf("failed to open config: %w", err)
    }
    defer file.Close()

    var config Config
    if err := json.NewDecoder(file).Decode(&config); err != nil {
        return nil, fmt.Errorf("failed to parse config: %w", err)
    }

    return &config, nil
}
"""

GO_IMPORTS_ALIASED = """\
package main

import (
    "fmt"
    f "fmt"
    . "strings"
    _ "database/sql"
)
"""

GO_GENERATED = """\
// Code generated by stringer -type=Status; DO NOT EDIT.

package model

import "strconv"

func (s Status) String() string {
    return strconv.FormatInt(int64(s), 10)
}
"""

GO_INIT = """\
package main

import "database/sql"

func init() {
    sql.Register("custom", &customDriver{})
}
"""

GO_SINGLE_IMPORT = """\
package main

import "fmt"

func main() {
    fmt.Println("hello")
}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_go(source: str) -> Tree:
    tree = parse_file(source, Language.GO)
    assert tree is not None
    return tree


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


class TestGoParsing:
    def test_parse_valid_go_file(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        assert tree.root_node.type == "source_file"
        assert not tree.root_node.has_error

    def test_parse_struct(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        assert not tree.root_node.has_error

    def test_parse_interface(self) -> None:
        tree = _parse_go(GO_INTERFACE)
        assert not tree.root_node.has_error

    def test_parse_goroutine(self) -> None:
        tree = _parse_go(GO_GOROUTINE)
        assert not tree.root_node.has_error

    def test_parse_defer(self) -> None:
        tree = _parse_go(GO_ERROR_HANDLING)
        assert not tree.root_node.has_error

    def test_parse_channel_operations(self) -> None:
        source = """\
package main

func producer(ch chan<- int) {
    ch <- 42
}

func consumer(ch <-chan int) {
    value := <-ch
    _ = value
}
"""
        tree = _parse_go(source)
        assert not tree.root_node.has_error

    def test_parse_error_handling_pattern(self) -> None:
        tree = _parse_go(GO_ERROR_HANDLING)
        assert not tree.root_node.has_error


# ---------------------------------------------------------------------------
# Scope detection
# ---------------------------------------------------------------------------


class TestGoScopeDetection:
    def test_function_scope(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        # NewService function starts at line 17
        scope = find_go_scope(tree, 18)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "NewService"

    def test_function_with_parameters(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        scope = find_go_scope(tree, 18)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "NewService"

    def test_function_with_return_values(self) -> None:
        tree = _parse_go(GO_ERROR_HANDLING)
        scope = find_go_scope(tree, 5)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "LoadConfig"

    def test_method_scope_pointer_receiver(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        # Process method with pointer receiver
        scope = find_go_scope(tree, 22)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "Process"

    def test_method_scope_value_receiver(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        # GetConfig method with value receiver
        scope = find_go_scope(tree, 26)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "GetConfig"

    def test_anonymous_function_scope(self) -> None:
        tree = _parse_go(GO_GOROUTINE)
        # Inside the goroutine anonymous func
        scope = find_go_scope(tree, 6)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "<anonymous>"

    def test_no_scope_at_package_level(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        # Line 1 is `package main`
        scope = find_go_scope(tree, 1)
        assert scope is None

    def test_init_function(self) -> None:
        tree = _parse_go(GO_INIT)
        scope = find_go_scope(tree, 6)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "init"

    def test_main_function(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        scope = find_go_scope(tree, 30)
        assert scope is not None
        assert scope.type == "function"
        assert scope.name == "main"

    def test_scope_via_dispatcher(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        scope = find_enclosing_scope(tree, 18, Language.GO)
        assert scope is not None
        assert scope.name == "NewService"


# ---------------------------------------------------------------------------
# Import extraction
# ---------------------------------------------------------------------------


class TestGoImportExtraction:
    def test_single_import(self) -> None:
        tree = _parse_go(GO_SINGLE_IMPORT)
        imports = extract_go_imports(tree)
        assert len(imports) == 1
        assert imports[0].module == "fmt"

    def test_grouped_imports(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        imports = extract_go_imports(tree)
        assert len(imports) == 5
        modules = [imp.module for imp in imports]
        assert "fmt" in modules
        assert "strings" in modules
        assert "net/http" in modules
        assert "github.com/myorg/myapp/internal/helper" in modules
        assert "github.com/lib/pq" in modules

    def test_aliased_import(self) -> None:
        tree = _parse_go(GO_IMPORTS_ALIASED)
        imports = extract_go_imports(tree)
        aliased = [imp for imp in imports if imp.alias == "f"]
        assert len(aliased) == 1
        assert aliased[0].module == "fmt"

    def test_dot_import(self) -> None:
        tree = _parse_go(GO_IMPORTS_ALIASED)
        imports = extract_go_imports(tree)
        dot_imports = [imp for imp in imports if imp.alias == "."]
        assert len(dot_imports) == 1
        assert dot_imports[0].module == "strings"

    def test_blank_import(self) -> None:
        tree = _parse_go(GO_IMPORTS_ALIASED)
        imports = extract_go_imports(tree)
        blank = [imp for imp in imports if imp.alias == "_"]
        assert len(blank) == 1
        assert blank[0].module == "database/sql"

    def test_third_party_import(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        imports = extract_go_imports(tree)
        pq_import = [imp for imp in imports if imp.module == "github.com/lib/pq"]
        assert len(pq_import) == 1
        assert pq_import[0].alias == "_"

    def test_extract_imports_via_dispatcher(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        imports = extract_imports(tree, Language.GO)
        assert len(imports) == 5


# ---------------------------------------------------------------------------
# Symbol usage detection
# ---------------------------------------------------------------------------


class TestGoSymbolUsage:
    def test_used_symbols_in_function(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        # Process method body: uses helper, strings
        symbols = find_go_used_symbols(tree, 21, 23)
        assert "helper" in symbols
        assert "strings" in symbols

    def test_used_symbols_exclude_builtins(self) -> None:
        source = """\
package main

func foo() {
    x := make([]int, 10)
    y := len(x)
    _ = y
}
"""
        tree = _parse_go(source)
        symbols = find_go_used_symbols(tree, 4, 6, exclude_builtins=True)
        assert "make" not in symbols
        assert "len" not in symbols

    def test_defined_symbols_excluded(self) -> None:
        source = """\
package main

func process() {
    x := 42
    y := x + 1
    _ = y
}
"""
        tree = _parse_go(source)
        # x is defined via short var declaration on line 4, then used on line 5
        symbols = find_go_used_symbols(tree, 4, 6)
        # x is defined locally, should not appear as external
        assert "x" not in symbols

    def test_selector_field_excluded(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        # `helper.Sanitize` — Sanitize should be excluded as selector field
        symbols = find_go_used_symbols(tree, 21, 23)
        assert "Sanitize" not in symbols
        assert "TrimSpace" not in symbols

    def test_via_dispatcher(self) -> None:
        tree = _parse_go(GO_PACKAGE)
        symbols = find_used_symbols(tree, 21, 23, Language.GO)
        assert "helper" in symbols


# ---------------------------------------------------------------------------
# Language detection
# ---------------------------------------------------------------------------


class TestGoLanguageDetection:
    def test_detect_go_extension(self) -> None:
        assert detect_language("cmd/server/main.go") == Language.GO

    def test_detect_go_uppercase(self) -> None:
        assert detect_language("main.GO") == Language.GO


# ---------------------------------------------------------------------------
# First-party detection
# ---------------------------------------------------------------------------


class TestGoFirstParty:
    @pytest.fixture(autouse=True)
    def _clear_cache(self) -> None:
        clear_go_mod_cache()

    def test_stdlib_is_not_first_party(self) -> None:
        project = Path("/fake/project")
        assert is_first_party_go("fmt", project) is False

    def test_stdlib_nested_not_first_party(self) -> None:
        project = Path("/fake/project")
        assert is_first_party_go("net/http", project) is False
        assert is_first_party_go("crypto/tls", project) is False

    def test_first_party_via_go_mod(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        assert is_first_party_go("github.com/myorg/myapp/internal/utils", tmp_path) is True

    def test_third_party_import(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        assert is_first_party_go("github.com/other/package", tmp_path) is False

    def test_internal_package_first_party(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        assert is_first_party_go("github.com/myorg/myapp/internal/auth", tmp_path) is True

    def test_exact_module_path_first_party(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        assert is_first_party_go("github.com/myorg/myapp", tmp_path) is True

    def test_no_go_mod_returns_false(self, tmp_path: Path) -> None:
        assert is_first_party_go("github.com/myorg/myapp/pkg", tmp_path) is False

    def test_third_party_patterns_respected(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        assert is_first_party_go("vendor/github.com/lib/pq", tmp_path, ["vendor/"]) is False


# ---------------------------------------------------------------------------
# Symbol resolution
# ---------------------------------------------------------------------------


class TestGoSymbolResolution:
    @pytest.fixture(autouse=True)
    def _clear_cache(self) -> None:
        clear_go_mod_cache()

    def test_resolve_first_party_import(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        # Create the package directory with a Go file
        pkg_dir = tmp_path / "internal" / "utils"
        pkg_dir.mkdir(parents=True)
        go_file = pkg_dir / "utils.go"
        go_file.write_text("package utils\n")

        imports = [Import(module="github.com/myorg/myapp/internal/utils", is_relative=False)]
        result = resolve_go_symbol("utils", imports, tmp_path)
        assert result is not None
        assert result.name == "utils.go"

    def test_resolve_skips_test_files(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        pkg_dir = tmp_path / "internal" / "utils"
        pkg_dir.mkdir(parents=True)
        (pkg_dir / "utils_test.go").write_text("package utils\n")
        (pkg_dir / "utils.go").write_text("package utils\n")

        imports = [Import(module="github.com/myorg/myapp/internal/utils", is_relative=False)]
        result = resolve_go_symbol("utils", imports, tmp_path)
        assert result is not None
        assert result.name == "utils.go"

    def test_resolve_third_party_returns_none(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        imports = [Import(module="github.com/other/pkg", is_relative=False)]
        result = resolve_go_symbol("pkg", imports, tmp_path)
        assert result is None

    def test_resolve_blank_import_skipped(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        imports = [Import(module="github.com/lib/pq", alias="_", is_relative=False)]
        result = resolve_go_symbol("pq", imports, tmp_path)
        assert result is None

    def test_resolve_aliased_import(self, tmp_path: Path) -> None:
        go_mod = tmp_path / "go.mod"
        go_mod.write_text("module github.com/myorg/myapp\n\ngo 1.21\n")

        pkg_dir = tmp_path / "internal" / "utils"
        pkg_dir.mkdir(parents=True)
        (pkg_dir / "utils.go").write_text("package utils\n")

        imports = [Import(module="github.com/myorg/myapp/internal/utils", alias="u", is_relative=False)]
        result = resolve_go_symbol("u", imports, tmp_path)
        assert result is not None


# ---------------------------------------------------------------------------
# Vendor path filtering
# ---------------------------------------------------------------------------


class TestGoVendorFiltering:
    def test_skip_vendor_directory(self) -> None:
        config = DiffguardConfig()
        assert "vendor/" in config.third_party_patterns


# ---------------------------------------------------------------------------
# Generated file detection
# ---------------------------------------------------------------------------


class TestGoGeneratedFileDetection:
    def test_generated_header(self) -> None:
        lines = GO_GENERATED.splitlines()
        assert is_generated_file("status_string.go", lines, Language.GO) is True

    def test_generated_header_with_build_tags(self) -> None:
        source = """\
//go:build linux
// +build linux

// Code generated by mockgen; DO NOT EDIT.

package mock
"""
        assert is_generated_file("mock_repo.go", source.splitlines(), Language.GO) is True

    def test_protobuf_generated(self) -> None:
        assert is_generated_file("api/v1/service.pb.go", [], Language.GO) is True

    def test_stringer_generated(self) -> None:
        assert is_generated_file("status_string.go", [], Language.GO) is True

    def test_mock_prefix_generated(self) -> None:
        assert is_generated_file("mock_repository.go", [], Language.GO) is True

    def test_mock_suffix_generated(self) -> None:
        assert is_generated_file("repository_mock.go", [], Language.GO) is True

    def test_gen_suffix_generated(self) -> None:
        assert is_generated_file("types_gen.go", [], Language.GO) is True

    def test_normal_go_file_not_generated(self) -> None:
        lines = ["package main\n", "\n", "func main() {\n", "}\n"]
        assert is_generated_file("main.go", lines, Language.GO) is False

    def test_non_matching_comment_not_generated(self) -> None:
        lines = ["// This is a normal file\n", "package main\n"]
        assert is_generated_file("main.go", lines, Language.GO) is False


# ---------------------------------------------------------------------------
# Makefile detection
# ---------------------------------------------------------------------------


class TestMakefileDetection:
    def test_detect_mk_extension(self) -> None:
        assert detect_language("build/rules.mk") == Language.MAKEFILE

    def test_detect_makefile_by_filename(self) -> None:
        assert detect_language("Makefile") == Language.MAKEFILE

    def test_detect_makefile_lowercase(self) -> None:
        assert detect_language("makefile") == Language.MAKEFILE

    def test_detect_gnumakefile(self) -> None:
        assert detect_language("GNUmakefile") == Language.MAKEFILE

    def test_detect_makefile_in_subdirectory(self) -> None:
        assert detect_language("build/Makefile") == Language.MAKEFILE

    def test_no_false_positive_dockerfile(self) -> None:
        assert detect_language("Dockerfile") is None

    def test_no_false_positive_license(self) -> None:
        assert detect_language("LICENSE") is None

    def test_no_false_positive_readme(self) -> None:
        # README has no extension, not in filename map
        assert detect_language("README") is None

    def test_no_ast_enrichment_for_makefiles(self) -> None:
        # Makefile has no tree-sitter grammar — scope detection returns None
        assert find_enclosing_scope.__module__  # just verify the function exists
        # No parser for MAKEFILE — the pipeline will skip AST enrichment

    def test_makefile_mk_in_path(self) -> None:
        assert detect_language("project/build/config.mk") == Language.MAKEFILE
