"""Tests for Ruby language support."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from diffguard.ast import (
    Language,
    detect_language,
    extract_imports,
    find_used_symbols,
    is_first_party,
    parse_file,
    resolve_symbol_definition,
)
from diffguard.ast.python import Import
from diffguard.ast.ruby import clear_gemfile_cache
from diffguard.ast.scope import find_enclosing_scope
from diffguard.config import DiffguardConfig
from diffguard.exclusions import is_generated_file
from diffguard.git import DiffFile, DiffHunk
from diffguard.pipeline import _filter_analyzable_files

if TYPE_CHECKING:
    from tree_sitter import Tree


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_ruby(source: str) -> Tree:
    """Parse Ruby source and return a tree-sitter Tree."""
    tree = parse_file(source, Language.RUBY)
    assert tree is not None
    return tree


def _make_diff_file(path: str) -> DiffFile:
    return DiffFile(
        old_path=path,
        new_path=path,
        hunks=[DiffHunk(old_start=1, old_count=1, new_start=1, new_count=1, lines=[("+", "x")])],
        is_new_file=False,
        is_deleted=False,
        is_binary=False,
    )


# ---------------------------------------------------------------------------
# Test fixtures
# ---------------------------------------------------------------------------

RUBY_MODULE_AND_CLASS = """\
require 'json'
require_relative './helper'

module MyApp
  module Services
    class Processor
      attr_reader :config

      def initialize(config)
        @config = config
      end

      def process(data)
        Helper.validate(data)
        JSON.parse(data)
      end

      def self.default
        new({})
      end
    end
  end
end
"""

RUBY_BLOCKS = """\
class DataProcessor
  def process_all(items)
    items.each do |item|
      puts item
    end

    items.map { |x| x.upcase }
  end

  def with_callback(&block)
    block.call(self)
  end
end
"""

RUBY_LAMBDA = """\
class Calculator
  OPERATIONS = {
    add: ->(a, b) { a + b },
    subtract: ->(a, b) { a - b },
  }

  def calculate(op, a, b)
    OPERATIONS[op].call(a, b)
  end
end
"""

RUBY_INHERITANCE = """\
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end
"""

RUBY_HEREDOC = """\
class QueryBuilder
  def build_query(table, conditions)
    <<~SQL
      SELECT * FROM #{table}
      WHERE #{conditions}
    SQL
  end
end
"""

RUBY_IMPORTS = """\
require 'json'
require_relative './helper'
load 'config.rb'
autoload :MyClass, 'my_class'
require 'net/http'
"""

RUBY_GENERATED = """\
# This file is auto-generated by rails db:schema:dump
# Do not edit this file directly.

ActiveRecord::Schema.define(version: 2024_01_01_000000) do
  create_table "users" do |t|
    t.string "name"
  end
end
"""


# ---------------------------------------------------------------------------
# Language Detection
# ---------------------------------------------------------------------------


class TestRubyLanguageDetection:
    def test_detect_rb_extension(self) -> None:
        assert detect_language("app/models/user.rb") == Language.RUBY

    def test_detect_rb_simple(self) -> None:
        assert detect_language("helper.rb") == Language.RUBY

    def test_detect_non_ruby(self) -> None:
        assert detect_language("src/main.py") != Language.RUBY

    def test_parse_valid_ruby(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        assert tree is not None
        assert tree.root_node.type == "program"


# ---------------------------------------------------------------------------
# Scope Detection
# ---------------------------------------------------------------------------


class TestRubyScopeDetection:
    def test_method_scope(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # Line inside `initialize` method (line 10: `@config = config`)
        scope = find_enclosing_scope(tree, 10, Language.RUBY)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "initialize"

    def test_method_with_arguments(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # Line inside `process` method (line 14: `Helper.validate(data)`)
        scope = find_enclosing_scope(tree, 14, Language.RUBY)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "process"

    def test_class_method_scope(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # Line inside `self.default` method (line 19: `new({})`)
        scope = find_enclosing_scope(tree, 19, Language.RUBY)
        assert scope is not None
        assert scope.type == "method"
        assert scope.name == "default"

    def test_class_scope(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # Line inside class body but not in method (line 7: `attr_reader :config`)
        scope = find_enclosing_scope(tree, 7, Language.RUBY)
        assert scope is not None
        assert scope.type == "class"
        assert scope.name == "Processor"

    def test_class_with_inheritance(self) -> None:
        tree = _parse_ruby(RUBY_INHERITANCE)
        # Line inside class (line 2: `before_action :authenticate_user!`)
        scope = find_enclosing_scope(tree, 2, Language.RUBY)
        assert scope is not None
        assert scope.type == "class"
        assert scope.name == "ApplicationController"

    def test_module_scope(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # Line 5: module Services (the Services module contains the class)
        # Line 5 is `module Services` — inside outer MyApp module
        scope = find_enclosing_scope(tree, 5, Language.RUBY)
        assert scope is not None
        assert scope.type == "module"

    def test_nested_module_scope(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # The inner Services module contains the class — check a line inside Services but outside Processor
        # Since Processor fills all of Services body, just check that module detection works
        scope = find_enclosing_scope(tree, 4, Language.RUBY)
        assert scope is not None
        assert scope.type == "module"
        assert scope.name == "MyApp"

    def test_do_block_scope(self) -> None:
        tree = _parse_ruby(RUBY_BLOCKS)
        # Line inside do block (line 4: `puts item`)
        scope = find_enclosing_scope(tree, 4, Language.RUBY)
        assert scope is not None
        assert scope.type == "block"

    def test_brace_block_scope(self) -> None:
        tree = _parse_ruby(RUBY_BLOCKS)
        # Line with `items.map { |x| x.upcase }` (line 7)
        scope = find_enclosing_scope(tree, 7, Language.RUBY)
        assert scope is not None
        # Could be block or method depending on nesting
        assert scope.type in ("block", "method")

    def test_lambda_scope(self) -> None:
        tree = _parse_ruby(RUBY_LAMBDA)
        # Line 3: `add: ->(a, b) { a + b },` — the lambda is on this line
        scope = find_enclosing_scope(tree, 3, Language.RUBY)
        assert scope is not None
        # Lambda, block, or class are all valid depending on how tree-sitter nests it
        assert scope.type in ("lambda", "block", "class")

    def test_no_scope_at_top_level(self) -> None:
        source = "x = 1\n"
        tree = _parse_ruby(source)
        scope = find_enclosing_scope(tree, 1, Language.RUBY)
        assert scope is None


# ---------------------------------------------------------------------------
# Import Extraction
# ---------------------------------------------------------------------------


class TestRubyImportExtraction:
    def test_require_call(self) -> None:
        tree = _parse_ruby(RUBY_IMPORTS)
        imports = extract_imports(tree, Language.RUBY)
        modules = [imp.module for imp in imports]
        assert "json" in modules

    def test_require_relative_call(self) -> None:
        tree = _parse_ruby(RUBY_IMPORTS)
        imports = extract_imports(tree, Language.RUBY)
        relative_imports = [imp for imp in imports if imp.is_relative]
        assert len(relative_imports) >= 1
        assert any(imp.module == "./helper" for imp in relative_imports)

    def test_load_call(self) -> None:
        tree = _parse_ruby(RUBY_IMPORTS)
        imports = extract_imports(tree, Language.RUBY)
        modules = [imp.module for imp in imports]
        assert "config.rb" in modules

    def test_autoload_call(self) -> None:
        tree = _parse_ruby(RUBY_IMPORTS)
        imports = extract_imports(tree, Language.RUBY)
        modules = [imp.module for imp in imports]
        assert "my_class" in modules

    def test_multiple_requires(self) -> None:
        tree = _parse_ruby(RUBY_IMPORTS)
        imports = extract_imports(tree, Language.RUBY)
        assert len(imports) == 5

    def test_require_with_path(self) -> None:
        tree = _parse_ruby(RUBY_IMPORTS)
        imports = extract_imports(tree, Language.RUBY)
        modules = [imp.module for imp in imports]
        assert "net/http" in modules


# ---------------------------------------------------------------------------
# Symbol Usage Detection
# ---------------------------------------------------------------------------


class TestRubySymbolUsage:
    def test_used_symbols_in_method(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # `process` method lines 13-16: uses Helper and JSON
        symbols = find_used_symbols(tree, 13, 16, Language.RUBY)
        assert "Helper" in symbols

    def test_excludes_builtins(self) -> None:
        tree = _parse_ruby(RUBY_BLOCKS)
        # process_all method uses `puts`
        symbols = find_used_symbols(tree, 2, 8, Language.RUBY, exclude_builtins=True)
        assert "puts" not in symbols

    def test_local_definitions_excluded(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        # initialize method: `config` is a parameter
        symbols = find_used_symbols(tree, 9, 11, Language.RUBY)
        assert "config" not in symbols


# ---------------------------------------------------------------------------
# First-Party Detection
# ---------------------------------------------------------------------------


class TestRubyFirstPartyDetection:
    def test_require_relative_always_first_party(self) -> None:
        root = Path("/project")
        assert is_first_party("./helper", root, [], Language.RUBY, is_relative=True) is True

    def test_stdlib_not_first_party(self) -> None:
        root = Path("/project")
        assert is_first_party("json", root, [], Language.RUBY) is False

    def test_gem_from_gemfile_not_first_party(self, tmp_path: Path) -> None:
        clear_gemfile_cache()
        (tmp_path / "Gemfile").write_text("source 'https://rubygems.org'\ngem 'rails'\ngem 'puma'\n")
        assert is_first_party("rails", tmp_path, [], Language.RUBY) is False

    def test_first_party_by_local_file(self, tmp_path: Path) -> None:
        clear_gemfile_cache()
        lib_dir = tmp_path / "lib"
        lib_dir.mkdir()
        (lib_dir / "my_helper.rb").write_text("# helper")
        assert is_first_party("my_helper", tmp_path, [], Language.RUBY) is True

    def test_unknown_module_without_local_file(self, tmp_path: Path) -> None:
        clear_gemfile_cache()
        assert is_first_party("nonexistent_module", tmp_path, [], Language.RUBY) is False


# ---------------------------------------------------------------------------
# Symbol Resolution
# ---------------------------------------------------------------------------


class TestRubySymbolResolution:
    def test_resolve_require_relative(self, tmp_path: Path) -> None:
        helper_file = tmp_path / "app" / "services" / "helper.rb"
        helper_file.parent.mkdir(parents=True)
        helper_file.write_text("class Helper; end")

        current_file = tmp_path / "app" / "services" / "processor.rb"
        imports = [Import(module="./helper", is_relative=True)]
        result = resolve_symbol_definition("Helper", imports, tmp_path, current_file, Language.RUBY)
        assert result is not None
        assert result == helper_file

    def test_resolve_require_to_lib(self, tmp_path: Path) -> None:
        helper_file = tmp_path / "lib" / "my_app" / "helper.rb"
        helper_file.parent.mkdir(parents=True)
        helper_file.write_text("class Helper; end")

        imports = [Import(module="my_app/helper")]
        result = resolve_symbol_definition("Helper", imports, tmp_path, None, Language.RUBY)
        assert result is not None
        assert result == helper_file

    def test_resolve_unresolvable_returns_none(self, tmp_path: Path) -> None:
        imports = [Import(module="nonexistent")]
        result = resolve_symbol_definition("Helper", imports, tmp_path, None, Language.RUBY)
        assert result is None


# ---------------------------------------------------------------------------
# Vendor Path Filtering
# ---------------------------------------------------------------------------


class TestRubyVendorPathFiltering:
    def test_skip_vendor_bundle(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("vendor/bundle/ruby/3.3.0/gems/rails-7.1/lib/rails.rb")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 0

    def test_skip_vendor_ruby(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("vendor/ruby/lib/some_gem.rb")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 0

    def test_skip_bundle_dir(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file(".bundle/config.rb")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 0

    def test_normal_ruby_file_kept(self) -> None:
        config = DiffguardConfig()
        files = [_make_diff_file("app/models/user.rb")]
        result = _filter_analyzable_files(files, config)
        assert len(result) == 1


# ---------------------------------------------------------------------------
# Generated File Detection
# ---------------------------------------------------------------------------


class TestRubyGeneratedFileDetection:
    def test_skip_db_schema_rb(self) -> None:
        assert is_generated_file("db/schema.rb", [], Language.RUBY) is True

    def test_skip_auto_generated_header(self) -> None:
        lines = RUBY_GENERATED.splitlines()
        assert is_generated_file("app/models/generated.rb", lines, Language.RUBY) is True

    def test_normal_ruby_not_generated(self) -> None:
        lines = RUBY_MODULE_AND_CLASS.splitlines()
        assert is_generated_file("app/services/processor.rb", lines, Language.RUBY) is False

    def test_skip_generated_by_header(self) -> None:
        lines = ["# Generated by some tool", "class Foo; end"]
        assert is_generated_file("lib/foo.rb", lines, Language.RUBY) is True

    def test_filter_analyzable_skips_generated_file(self, tmp_path: Path) -> None:
        """A Ruby file with auto-generated header should be filtered out by the pipeline."""
        models_dir = tmp_path / "app" / "models"
        models_dir.mkdir(parents=True)
        (models_dir / "generated.rb").write_text(RUBY_GENERATED)

        rel_path = "app/models/generated.rb"
        diff_files = [_make_diff_file(rel_path)]
        config = DiffguardConfig()
        result = _filter_analyzable_files(diff_files, config, project_root=tmp_path)
        assert len(result) == 0


# ---------------------------------------------------------------------------
# Parsing Features
# ---------------------------------------------------------------------------


class TestRubyParsingFeatures:
    def test_parse_module_and_class(self) -> None:
        tree = _parse_ruby(RUBY_MODULE_AND_CLASS)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_blocks(self) -> None:
        tree = _parse_ruby(RUBY_BLOCKS)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_lambda(self) -> None:
        tree = _parse_ruby(RUBY_LAMBDA)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_inheritance(self) -> None:
        tree = _parse_ruby(RUBY_INHERITANCE)
        assert tree is not None
        assert not tree.root_node.has_error

    def test_parse_heredoc(self) -> None:
        tree = _parse_ruby(RUBY_HEREDOC)
        assert tree is not None

    def test_parse_safe_navigation(self) -> None:
        source = "user&.name\n"
        tree = _parse_ruby(source)
        assert tree is not None

    def test_parse_symbols(self) -> None:
        source = ':symbol\n:"quoted symbol"\n'
        tree = _parse_ruby(source)
        assert tree is not None

    def test_parse_attr_accessor(self) -> None:
        source = """\
class User
  attr_accessor :name, :email
end
"""
        tree = _parse_ruby(source)
        assert tree is not None
        assert not tree.root_node.has_error
